{config, ...}: {
  programs.niri.settings.binds = with config.lib.niri.actions; {
    "Mod+Shift+Q".action = close-window;
    "Mod+Return".action = spawn "kitty";
    "Mod+Space".action = spawn "sherlock";
    "Print".action = screenshot {show-pointer = true;};
    "Mod+H".action = focus-column-left;
    "Mod+J".action = focus-window-or-workspace-down;
    "Mod+K".action = focus-window-or-workspace-up;
    "Mod+L".action = focus-column-right;
    "Mod+Shift+H".action = move-column-left;
    "Mod+Shift+J".action = move-window-down-or-to-workspace-down;
    "Mod+Shift+K".action = move-window-up-or-to-workspace-up;
    "Mod+Shift+L".action = move-column-right;
    "Mod+Ctrl+H".action = move-workspace-to-monitor-left;
    "Mod+Ctrl+J".action = move-workspace-to-monitor-down;
    "Mod+Ctrl+K".action = move-workspace-to-monitor-up;
    "Mod+Ctrl+L".action = move-workspace-to-monitor-right;
    "Mod+U".action = focus-workspace-down;
    "Mod+I".action = focus-workspace-up;
    "Mod+Shift+U".action = move-column-to-workspace-down;
    "Mod+Shift+I".action = move-column-to-workspace-up;
    "Mod+Ctrl+U".action = move-workspace-down;
    "Mod+Ctrl+I".action = move-workspace-up;
    "Mod+BracketLeft".action = consume-or-expel-window-left;
    "Mod+BracketRight".action = consume-or-expel-window-right;
    "Mod+Comma".action = consume-window-into-column;
    "Mod+Period".action = expel-window-from-column;
    "Mod+F".action = maximize-column;
    "Mod+Shift+F".action = fullscreen-window;
    "Mod+C".action = center-column;
    "Mod+R".action = switch-preset-column-width;
    "Mod+Minus".action = set-column-width "-5%";
    "Mod+Equal".action = set-column-width "+5%";
    "Mod+Shift+Minus".action = set-window-height "-5%";
    "Mod+Shift+Equal".action = set-window-height "+5%";
    "XF86AudioRaiseVolume".action = spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "0.1+" "-l" "1";
    "XF86AudioLowerVolume".action = spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "0.1-";
    "XF86AudioMute".action = spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle";
    "XF86AudioMicMute".action = spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SOURCE@" "toggle";
    "XF86MonBrightnessUp".action = spawn "brightnessctl" "set" "10%+";
    "XF86MonBrightnessDown".action = spawn "brightnessctl" "set" "10%-";
  };
}
